# devtools::install_version("matchingMarkets", "0.3-6")
print("#----------------------- 0.3.6")
rm(list = ls())
devtools::load_all()
predictions <- sample(c(0,1), 100, TRUE, c(3, 1))
references  <- sample(c(0,1), 100, TRUE, c(4,1))
get_transition_info(predictions, references, 10)

# install.packages("matchingMarkets")
print("#----------------------- 1.0.1")
rm(list = ls())
devtools::load_all()
predictions <- sample(c(0,1), 100, TRUE, c(3, 1))
references  <- sample(c(0,1), 100, TRUE, c(4,1))
get_transition_info(predictions, references, 10)
